### ISSUE TITLE
chore(scrutiny): simplify collector

### ISSUE THREAD

**Issue by uhthomas** [ahgraber/homelab-gitops-k3s#2319]
I noticed you're using an init container to set the host id for the collector.

https://github.com/ahgraber/homelab-gitops-k3s/blob/b3d5e0554998ae6ddac7e60fa259a9eb10a32690/kubernetes/apps/monitoring/scrutiny/app/helmrelease-collector.yaml#L32

This shouldn't be necessary? There is a [`COLLECTOR_HOST_ID`](https://github.com/AnalogJ/scrutiny/blob/d54a0abc8c1cc6edadca7e8810b1b1b1917a7902/collector/cmd/collector-metrics/collector-metrics.go#L177-L182) environment variable.

**Comment by ahgraber** [comment]
You are correct, thanks!
